import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  ArrowDown, ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, Bell, CalendarDays, Check,
  CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, ClipboardList, Clock3,
  CreditCard, ExternalLink, Eye, Filter, Globe2, Heart, LayoutDashboard, LifeBuoy, LogOut,
  Mail, Menu, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Sparkles, Star, Utensils,
  Users, X, Building2, BedDouble, Package, TrendingUp, WandSparkles, Pencil, Trash2
} from 'lucide-react';
import './style.css';

const seed = {
  bookings: [
    {id:1,name:'Aarav & Meera Sharma',event:'Wedding reception',date:'2026-10-18',guests:450,venue:'The Grand Pavilion',status:'Confirmed',amount:18500,avatar:'AM',color:'peach'},
    {id:2,name:'Rohan & Sanya Kapoor',event:'Engagement',date:'2026-10-21',guests:180,venue:'The Garden Room',status:'Pending',amount:8200,avatar:'RS',color:'lavender'},
    {id:3,name:'Priya Malhotra',event:'Mehendi celebration',date:'2026-10-24',guests:250,venue:'The Grand Pavilion',status:'Confirmed',amount:12750,avatar:'PM',color:'sage'},
    {id:4,name:'Kabir & Naina Verma',event:'Wedding ceremony',date:'2026-10-26',guests:600,venue:'The Grand Pavilion',status:'Confirmed',amount:24600,avatar:'KN',color:'blue'},
    {id:5,name:'Arjun & Diya Singh',event:'Sangeet night',date:'2026-10-29',guests:320,venue:'The Garden Room',status:'Inquiry',amount:14800,avatar:'AD',color:'yellow'},
  ],
  venues:[{id:1,name:'The Grand Pavilion',type:'Ballroom',capacity:700,events:18,image:'photo-1519167758481-83f550bb49b3'},{id:2,name:'The Garden Room',type:'Garden estate',capacity:250,events:12,image:'photo-1519741497674-611481863552'}],
  assets:[{id:1,name:'Gold Chiavari chair',category:'Furniture',qty:450,price:8,icon:'chair'},{id:2,name:'Ivory table linen',category:'Decor',qty:80,price:24,icon:'linen'},{id:3,name:'Floral arch installation',category:'Decor',qty:4,price:680,icon:'flower'},{id:4,name:'Wireless microphone set',category:'AV & Tech',qty:6,price:85,icon:'mic'}],
  menu:[{id:1,name:'Royal wedding buffet',category:'Food package',price:68,detail:'Per guest · 12 dishes'},{id:2,name:'Live chaat station',category:'Starter',price:14,detail:'Per guest · Live counter'},{id:3,name:'Rose & pistachio kulfi',category:'Dessert',price:9,detail:'Per guest · 2 flavours'},{id:4,name:'Welcome mocktail bar',category:'Beverage',price:12,detail:'Per guest · 3 hours'}]
};
const money = n => '$' + Number(n).toLocaleString('en-US');
const getData = () => { try { const d=JSON.parse(localStorage.getItem('merrage-data')); return d ? {...seed,...d} : seed; } catch { return seed; } };
const saveData = d => { try {localStorage.setItem('merrage-data',JSON.stringify(d));} catch {} };

function Brand({light=false}) { return <a className={`brand ${light?'brand-light':''}`} href="#home" onClick={e=>{e.preventDefault();window.dispatchEvent(new CustomEvent('view',{detail:'home'}))}}><span className="brand-mark"><Heart size={18} fill="currentColor" /></span><span>merrage<span className="brand-dot">.</span></span></a> }
function App(){
 const [data,setData]=useState(getData); const [view,setView]=useState('home'); const [modal,setModal]=useState(''); const [bookingEditing,setBookingEditing]=useState(null); const [resourceEditing,setResourceEditing]=useState(null); const [venueEditing,setVenueEditing]=useState(null); const [navOpen,setNavOpen]=useState(false); const [toast,setToast]=useState(''); const [backendReady,setBackendReady]=useState(false); const [user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('merrage-session'))}catch{return null}});
 useEffect(()=>{fetch('/api/data').then(r=>{if(!r.ok)throw Error('API unavailable');return r.json()}).then(serverData=>{if(serverData?.bookings)setData(serverData)}).catch(()=>{}).finally(()=>setBackendReady(true))},[]);
 useEffect(()=>{saveData(data);if(backendReady)fetch('/api/data',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).catch(()=>{})},[data,backendReady]);
 useEffect(()=>{const f=e=>{setView(e.detail);window.scrollTo({top:0,behavior:'smooth'})};window.addEventListener('view',f);return()=>window.removeEventListener('view',f)},[]);
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),2600)};
 const update=(key,val)=>setData(d=>({...d,[key]:val}));
 const openView=v=>{setView(v);setNavOpen(false);window.scrollTo({top:0,behavior:'smooth'})};
 const enterDashboard=account=>{if(account){setUser(account);try{localStorage.setItem('merrage-session',JSON.stringify(account))}catch{}}openView(account?.role==='event-client'?'booking':'dashboard')};
 const openBooking=item=>{setBookingEditing(item||null);setModal('booking')};const openResource=item=>{setResourceEditing(item||null);setModal('resource')};const openVenue=item=>{setVenueEditing(item||null);setModal('venue')};
 return <>
 {view==='dashboard'? <Dashboard data={data} update={update} openView={openView} openModal={setModal} notify={notify} user={user} openBooking={openBooking} openResource={openResource} openVenue={openVenue}/> : view==='booking'? <BookingPage data={data} setData={setData} openView={openView} notify={notify}/> : <Landing openView={openView} openModal={setModal} navOpen={navOpen} setNavOpen={setNavOpen}/>}
 {modal==='login'&&<LoginModal close={()=>setModal('')} enter={enterDashboard} notify={notify}/>}
 {modal==='booking'&&<BookingModal close={()=>{setModal('');setBookingEditing(null)}} data={data} setData={setData} notify={notify} initial={bookingEditing}/>}
 {modal==='resource'&&<ResourceModal close={()=>{setModal('');setResourceEditing(null)}} initial={resourceEditing} onSave={item=>{const k=item.kind==='menu'?'menu':'assets';update(k,resourceEditing?data[k].map(x=>x.id===resourceEditing.id?{...x,...item}:x):[{...item,id:Date.now()},...data[k]]);setModal('');setResourceEditing(null);notify(resourceEditing?'Your changes have been saved.':'Your new item is ready to go.')}}/>}
 {modal==='venue'&&<VenueModal initial={venueEditing} close={()=>{setModal('');setVenueEditing(null)}} onSave={venue=>{update('venues',venueEditing?data.venues.map(v=>v.id===venueEditing.id?{...v,...venue}:v):[{...venue,id:Date.now()},...(data.venues||[])]);setModal('');setVenueEditing(null);notify(venueEditing?'Venue details updated.':'Venue added to your collection.')}}/>}
 {modal==='contact'&&<ContactModal close={()=>setModal('')} notify={notify}/>}
 {toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}</div>}
 </>;
}

function Landing({openView,openModal,navOpen,setNavOpen}){
 const [faq,setFaq]=useState(0); const [scrolled,setScrolled]=useState(false);
 useEffect(()=>{const f=()=>setScrolled(window.scrollY>20);window.addEventListener('scroll',f);return()=>window.removeEventListener('scroll',f)},[]);
 useEffect(()=>{const nodes=document.querySelectorAll('.intro,.product-grid,.venues-head,.venue-card,.solution-card,.testimonial,.pricing-head,.price-card,.faq-head,.faq-item,.cta-inner');document.documentElement.classList.add('motion-ready');if(!('IntersectionObserver'in window)){nodes.forEach(n=>n.classList.add('revealed'));return}const observer=new IntersectionObserver(entries=>entries.forEach((entry,index)=>{if(entry.isIntersecting){entry.target.style.transitionDelay=`${(index%3)*70}ms`;entry.target.classList.add('revealed');observer.unobserve(entry.target)}}),{threshold:.1});nodes.forEach(n=>observer.observe(n));return()=>observer.disconnect()},[]);
 const go=id=>{setNavOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};
 return <div className="landing" id="home">
  <header className={`site-header ${scrolled?'scrolled':''}`}><div className="nav-wrap"><Brand/><nav className={navOpen?'nav-open':''}>
   <a onClick={()=>go('product')}>Platform</a><a onClick={()=>go('venues')}>Venues</a><a onClick={()=>go('solutions')}>Solutions</a><a onClick={()=>go('pricing')}>Pricing</a><a onClick={()=>go('about')}>About</a>
  </nav><div className="nav-actions"><button className="login-link" onClick={()=>openModal('login')}>Log in</button><button className="button button-dark button-small" onClick={()=>openModal('contact')}>Book a demo <ArrowUpRight size={15}/></button></div><button className="mobile-menu" aria-label="Toggle menu" onClick={()=>setNavOpen(!navOpen)}>{navOpen?<X/>:<Menu/>}</button></div></header>
  <main>
   <section className="hero section-shell">
    <div className="hero-copy reveal"><div className="eyebrow"><span className="eyebrow-icon"><Sparkles size={14}/></span> THE VENUE OPERATING SYSTEM</div>
     <h1>Make every<br/>celebration <em>matter.</em></h1>
     <p className="hero-desc">The all-in-one platform for wedding venues, planners, and the people who make a day unforgettable.</p>
     <div className="hero-buttons"><button className="button button-dark" onClick={()=>openModal('contact')}>See Merrage in action <ArrowRight size={16}/></button><button className="text-link" onClick={()=>go('product')}><span className="play-icon">▶</span> Explore the platform</button></div>
     <div className="hero-proof"><div className="avatar-stack"><span>R</span><span>K</span><span>M</span><span>S</span></div><div><div className="stars">★★★★★</div><small>Loved by 1,200+ event professionals</small></div></div>
    </div>
    <div className="hero-visual reveal"><div className="hero-photo"/><div className="photo-shade"/><div className="photo-caption"><span>THE GRAND PAVILION</span><span>JAIPUR, INDIA <ArrowUpRight size={12}/></span></div>
     <div className="hero-float-card booking-float"><span className="float-icon"><CalendarDays size={17}/></span><div><b>It's a date!</b><small>New booking confirmed</small></div><span className="float-check"><Check size={14}/></span></div>
     <div className="hero-float-card revenue-float"><div className="revenue-top"><span>Monthly revenue</span><ArrowUpRight size={14}/></div><b>$48,290</b><small className="up-label">↗ 18.6% <span>vs. last month</span></small><div className="spark-bars">{[26,38,32,56,42,66,48,75,56,86,66,96].map((n,i)=><i key={i} style={{height:n+'%'}}/>)}</div></div>
     <div className="photo-badge"><Heart size={14} fill="currentColor"/> Every detail, in harmony</div>
    </div>
   </section>
   <section className="trust section-shell"><p>TRUSTED BY THE TEAMS BEHIND THE BIGGEST DAYS</p><div className="trust-logos"><span className="logo-serif">The<i> Willow</i> House</span><span className="logo-wide">AURELIA <small>ESTATES</small></span><span className="logo-script">amour events</span><span className="logo-serif">PALM & <i>pine</i></span><span className="logo-wide">SĀRĀ <small>COLLECTION</small></span></div></section>
   <section className="intro section-shell" id="about"><div className="section-kicker">A BETTER WAY TO CELEBRATE</div><div className="intro-grid"><h2>Less juggling.<br/><em>More magic.</em></h2><div className="intro-copy"><p>Running a venue should feel as special as the events you host. Merrage brings your bookings, team, menus, and money into one thoughtful place.</p><button className="inline-link" onClick={()=>go('solutions')}>Get to know us <ArrowUpRight size={15}/></button></div></div></section>
   <section className="product-section" id="product"><div className="section-shell product-grid"><div className="product-copy"><div className="section-kicker">YOUR WHOLE BUSINESS, IN SYNC</div><h2>One calm place<br/>to run it <em>all.</em></h2><p>From the first inquiry to the last dance, every moving piece stays beautifully connected.</p><div className="feature-list"><Feature icon={<CalendarDays/>} title="Bookings that book themselves" text="See every inquiry, tour, and confirmed date at a glance."/><Feature icon={<Utensils/>} title="Menus made memorable" text="Build per-plate packages, add-ons, and custom experiences."/><Feature icon={<Users/>} title="A team in the know" text="Give every person the right details at exactly the right time."/></div><button className="inline-link" onClick={()=>openModal('login')}>Explore the platform <ArrowRight size={15}/></button></div>
    <div className="product-showcase"><div className="showcase-top"><div className="tiny-brand"><Brand/></div><span className="showcase-date">OCTOBER 2026 <ChevronDown size={13}/></span></div><div className="showcase-greeting"><div><small>MONDAY, OCTOBER 12, 2026</small><h3>Good morning, Maya <span>✦</span></h3></div><button className="showcase-add" onClick={()=>openModal('booking')}><Plus size={15}/> New booking</button></div><div className="mini-stats"><div><small>UPCOMING EVENTS</small><b>24</b><span>↗ 12% this month</span></div><div><small>OCTOBER REVENUE</small><b>$48,290</b><span>↗ 18.6% this month</span></div><div><small>NEW INQUIRIES</small><b>18</b><span>6 need your reply</span></div></div><div className="showcase-calendar"><div className="cal-heading"><b>Upcoming events</b><span>View calendar <ArrowRight size={12}/></span></div>{[['18','SUN','Aarav & Meera Sharma','Wedding reception','confirmed'],['21','WED','Rohan & Sanya Kapoor','Engagement celebration','pending'],['24','SAT','Priya Malhotra','Mehendi celebration','confirmed']].map((a,i)=><div className="mini-event" key={a[2]}><div className="date-tile"><b>{a[0]}</b><small>{a[1]}</small></div><div className="mini-event-info"><b>{a[2]}</b><small>{a[3]} · The Grand Pavilion</small></div><span className={`mini-status ${a[4]}`}>{a[4]}</span><MoreHorizontal size={16}/></div>)}</div><div className="showcase-footer"><ShieldCheck size={14}/> Your business is looking lovely <span>View insights <ArrowUpRight size={12}/></span></div></div>
   </div></section>
   <section className="venues-section section-shell" id="venues"><div className="venues-head"><div><div className="section-kicker">THE PLACE MAKES THE MEMORY</div><h2>Made for places<br/>worth <em>remembering.</em></h2></div><p>From intimate garden ceremonies to grand ballroom celebrations, give every venue its own beautiful home online.</p></div><div className="venue-cards"><Venue img="photo-1519167758481-83f550bb49b3" title="The Grand Pavilion" place="JAIPUR, INDIA" tag="PALACE & BALLROOM"/><Venue img="photo-1519741497674-611481863552" title="The Willow Garden" place="UDAIPUR, INDIA" tag="GARDEN ESTATE"/><Venue img="photo-1511795409834-ef04bbd61622" title="The Glasshouse" place="GOA, INDIA" tag="COASTAL RETREAT"/></div><div className="venue-note"><span><span className="note-dot"/> Each venue gets its own custom website and booking journey.</span><button className="inline-link" onClick={()=>openModal('contact')}>See how it works <ArrowRight size={15}/></button></div></section>
   <section className="solutions-section" id="solutions"><div className="section-shell"><div className="solutions-title"><div className="section-kicker">THOUGHTFULLY BUILT FOR YOU</div><h2>Good things happen<br/>when it <em>just works.</em></h2></div><div className="solution-grid"><Solution icon={<Globe2/>} n="01" title="Your name. Your domain." desc="Put your venue in the spotlight with a polished, custom-branded booking site on your own domain."/><Solution icon={<ClipboardList/>} n="02" title="Details, beautifully handled." desc="Contracts, deposits, seating plans, menus, and add-ons—all organized around the event."/><Solution icon={<TrendingUp/>} n="03" title="Know where you stand." desc="A clear view of revenue, availability, and follow-ups helps you make your next great decision."/></div></div></section>
   <section className="testimonial section-shell"><div className="testimonial-mark">“</div><div className="testimonial-content"><div className="stars">★★★★★</div><blockquote>“Merrage gave us back the time to focus on what we're actually here for: making people's biggest days feel like their own.”</blockquote><div className="quote-author"><div className="author-photo">AS</div><div><b>Anika Shah</b><small>Founder, The Willow House</small></div><span className="quote-counter">01 <i>/ 03</i></span></div></div><div className="testimonial-side"><div className="testimonial-img"/><span>REAL PEOPLE. REAL CELEBRATIONS.</span></div></section>
   <section className="pricing section-shell" id="pricing"><div className="pricing-head"><div className="section-kicker">SIMPLE, HONEST PRICING</div><h2>A little more <em>room</em><br/>to do your thing.</h2><p>Start with the essentials. Grow into everything else.</p></div><div className="pricing-cards"><Price name="Essentials" amount="$79" text="For independent venues ready to feel more organized." features={['Branded venue page','Booking & inquiry manager','Up to 3 team members','Email support']} cta="Start your 14-day trial" click={()=>openModal('contact')}/><Price featured name="Signature" amount="$149" text="For growing teams making every detail count." features={['Everything in Essentials','Custom domain & branding','Menus, add-ons & inventory','Unlimited team members','Reports & revenue insights']} cta="Find your flow" click={()=>openModal('contact')}/><Price name="Collection" amount="Let’s talk" text="For multi-property groups and larger operations." features={['Everything in Signature','Multiple venue management','Dedicated onboarding','Priority support']} cta="Talk to our team" click={()=>openModal('contact')}/></div><small className="pricing-foot">All plans include a 14-day free trial. No credit card required.</small></section>
   <section className="faq-section section-shell" id="faq"><div className="faq-head"><div className="section-kicker">GOOD QUESTIONS</div><h2>Wondering <em>about</em><br/>something?</h2><p>We're a friendly bunch. If you don't see your question, just ask.</p><button className="inline-link" onClick={()=>openModal('contact')}>Talk to a real person <ArrowRight size={15}/></button></div><div className="faq-list">{[
    ['Is Merrage right for my kind of venue?','If you host weddings, private events, or celebrations of any kind—we built Merrage for you. From boutique gardens to multi-property resorts, your setup can be as unique as your venue.'],['Can I use my own domain name?','Absolutely. Every Signature plan and above can connect a custom domain, so couples see your name—not ours—at every step.'],['Can I manage food and add-on packages?','Yes. Create per-person menus, starter stations, bar packages, and venue extras. Add them to proposals and bookings in a few clicks.'],['How long does it take to get started?','Most venues are up and running in an afternoon. Our team will help you bring your venue page, packages, and existing bookings across.'],['Can I try it before I commit?','Of course. Your 14-day trial includes all the features in your chosen plan, and you won’t need a card to get started.']
   ].map((it,i)=><div className={`faq-item ${faq===i?'faq-open':''}`} key={it[0]}><button onClick={()=>setFaq(faq===i?-1:i)}><span>{it[0]}</span><span className="faq-plus">{faq===i?'−':'+'}</span></button>{faq===i&&<p>{it[1]}</p>}</div>)}</div></section>
   <section className="cta-section"><div className="cta-orb orb-one"/><div className="cta-orb orb-two"/><div className="section-shell cta-inner"><span className="cta-kicker"><Sparkles size={13}/> YOUR NEXT CHAPTER STARTS HERE</span><h2>Make room for<br/><em>more magic.</em></h2><p>Give your venue the care it gives every celebration.</p><button className="button button-cream" onClick={()=>openModal('contact')}>Let's find your flow <ArrowRight size={16}/></button><small>14 days on us · No card needed</small></div></section>
  </main>
  <footer className="footer"><div className="section-shell"><div className="footer-main"><div className="footer-brand"><Brand/><p>Helping the people behind<br/>the best days do their best work.</p><div className="social-links"><a href="#home" aria-label="Instagram">ig</a><a href="#home" aria-label="LinkedIn">in</a><a href="#home" aria-label="Pinterest">p</a></div></div><div className="footer-col"><b>THE PLATFORM</b><a onClick={()=>go('product')}>Features</a><a onClick={()=>go('pricing')}>Pricing</a><a onClick={()=>openModal('login')}>Log in</a><a onClick={()=>openModal('contact')}>Book a demo</a></div><div className="footer-col"><b>EXPLORE</b><a onClick={()=>go('venues')}>Venues</a><a onClick={()=>go('solutions')}>For planners</a><a onClick={()=>go('about')}>Our story</a><a onClick={()=>openView('booking')}>Find a venue</a></div><div className="footer-col"><b>HERE TO HELP</b><a onClick={()=>go('faq')}>FAQs</a><a onClick={()=>openModal('contact')}>Contact us</a><a href="mailto:hello@merrage.com">hello@merrage.com</a></div><div className="newsletter"><b>A little inspiration, now and then.</b><p>Thoughtful ideas for the people making it happen.</p><form onSubmit={e=>{e.preventDefault();e.target.reset();window.dispatchEvent(new CustomEvent('merrage-toast',{detail:'You’re on the list. See you in your inbox!'}))}}><input type="email" required placeholder="Your email address"/><button aria-label="Subscribe"><ArrowRight size={16}/></button></form></div></div><div className="footer-bottom"><span>© 2026 Merrage Technologies. Made for the moments that matter.</span><div><a href="#home">Privacy</a><a href="#home">Terms</a><span>Made with ♡ for celebrations</span></div></div></div></footer>
 </div>
}
function Feature({icon,title,text}){return <div className="feature-row"><span>{icon}</span><div><b>{title}</b><p>{text}</p></div></div>}
function Venue({img,title,place,tag}){return <article className="venue-card"><div className="venue-image" style={{backgroundImage:`url(https://images.unsplash.com/${img}?auto=format&fit=crop&w=1000&q=85)`}}><span>{tag}</span><button aria-label={`View ${title}`}><ArrowUpRight size={17}/></button></div><div className="venue-card-caption"><div><h3>{title}</h3><small>{place}</small></div><ArrowUpRight size={17}/></div></article>}
function Solution({icon,n,title,desc}){return <div className="solution-card"><div className="solution-top"><span>{icon}</span><i>{n}</i></div><h3>{title}</h3><p>{desc}</p><ArrowDownRight className="solution-arrow" size={19}/></div>}
function Price({name,amount,text,features,cta,featured,click}){return <div className={`price-card ${featured?'featured':''}`}>{featured&&<div className="popular-label">THE CROWD FAVORITE <Sparkles size={12}/></div>}<div className="price-name">{name}</div><div className="price-amount">{amount}{amount.startsWith('$')&&<small>/ month</small>}</div><p>{text}</p><button className={featured?'button button-dark':'button button-outline'} onClick={click}>{cta}<ArrowRight size={14}/></button><div className="price-divider"/><small className="includes">WHAT'S INCLUDED</small><ul>{features.map(f=><li key={f}><Check size={14}/>{f}</li>)}</ul></div>}
function ContactModal({close,notify}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal contact-modal"><button className="modal-close" onClick={close}><X size={19}/></button><div className="modal-kicker">LET'S MAKE IT HAPPEN</div><h2>Your venue deserves<br/><em>a little more.</em></h2><p>Tell us a bit about you. A real person from our team will be in touch to find your flow.</p><form onSubmit={e=>{e.preventDefault();close();notify('Thanks! Our team will be in touch shortly.')}}><label>Your name<input required placeholder="e.g. Maya Shah"/></label><label>Work email<input required type="email" placeholder="you@yourvenue.com"/></label><label>Venue or company<input required placeholder="The Willow House"/></label><button className="button button-dark">Request a conversation <ArrowRight size={15}/></button></form><small className="modal-note"><ShieldCheck size={13}/> Your details stay between us.</small></div></div>}
function LoginModal({close,enter,notify}){const [email,setEmail]=useState('maya@thewillowhouse.com');const [role,setRole]=useState('venue-owner');const [busy,setBusy]=useState(false);const signIn=async e=>{e.preventDefault();setBusy(true);let account={email,name:email.split('@')[0],role};try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:e.currentTarget.password.value,role})});if(!r.ok)throw Error('Please check your details and try again.');const result=await r.json();account=result.user;localStorage.setItem('merrage-token',result.token)}catch(err){if(err.message!=='Failed to fetch')notify(err.message)}finally{setBusy(false);close();enter(account);notify(`Welcome to Merrage, ${account.name}!`)}};return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal login-modal"><button className="modal-close" onClick={close}><X size={19}/></button><Brand/><div className="modal-kicker">WELCOME TO MERRAGE</div><h2>Good to see<br/><em>you again.</em></h2><p>Step back into your venue's happy place.</p><form onSubmit={signIn}><label>Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input name="password" type="password" required defaultValue="merrage2026"/></label><label>Sign in as<select value={role} onChange={e=>setRole(e.target.value)}><option value="venue-owner">Marriage hall owner</option><option value="staff">Venue staff</option><option value="saas-owner">Merrage SaaS owner</option><option value="event-client">Couple / event client</option></select></label><button type="button" className="forgot-link" onClick={()=>notify('Password reset instructions are on their way.')}>Forgot password?</button><button className="button button-dark" disabled={busy}>{busy?'Signing you in…':'Log in to Merrage'} {!busy&&<ArrowRight size={15}/>}</button></form><div className="demo-hint"><Sparkles size={14}/> Demo access — any email and password works</div><small className="modal-note">New to Merrage? <a onClick={()=>{close();window.dispatchEvent(new CustomEvent('view',{detail:'home'}));setTimeout(()=>document.getElementById('pricing')?.scrollIntoView({behavior:'smooth'}),150)}}>See plans</a></small></div></div>}

function Dashboard({data,update,openView,openModal,notify,user,openBooking,openResource,openVenue}){
 const [section,setSection]=useState(user?.role==='saas-owner'?'SaaS overview':'Overview');const [search,setSearch]=useState('');const [filter,setFilter]=useState('All bookings');const [sideOpen,setSideOpen]=useState(false);const [menuId,setMenuId]=useState(null);
 const bookings=data.bookings.filter(b=>(b.name+b.event+b.venue).toLowerCase().includes(search.toLowerCase())&&(filter==='All bookings'||b.status===filter));
 const nav=[...(user?.role==='saas-owner'?[['SaaS overview',LayoutDashboard]]:[['Overview',LayoutDashboard]]),['Bookings',CalendarDays],['Venues',Building2],['Menus & packages',Utensils],['Add-ons & assets',Package],['Clients',Users]];
 const createBooking=()=>openBooking();
 const editStatus=(id,status)=>{update('bookings',data.bookings.map(b=>b.id===id?{...b,status}:b));setMenuId(null);notify(`Booking marked ${status.toLowerCase()}.`)};
 return <div className="dashboard-shell"><aside className={`sidebar ${sideOpen?'sidebar-open':''}`}><div className="sidebar-brand"><Brand/><button className="sidebar-close" onClick={()=>setSideOpen(false)}><X/></button></div><div className="workspace-switch"><div className="workspace-avatar">W</div><div><b>{user?.role==='saas-owner'?'Merrage platform':'The Willow House'}</b><small>{user?.role==='saas-owner'?'SaaS owner workspace':user?.role==='staff'?'Staff workspace':'Venue workspace'}</small></div><ChevronDown size={14}/></div><div className="side-label">WORKSPACE</div><nav>{nav.map(([name,Icon])=><button key={name} className={`side-nav ${section===name?'active':''}`} onClick={()=>{setSection(name);setSideOpen(false)}}><Icon size={17}/>{name}{name==='Bookings'&&<i>{data.bookings.length}</i>}</button>)}</nav><div className="side-label side-manage">MANAGE</div><nav><button className={`side-nav ${section==='Team'?'active':''}`} onClick={()=>setSection('Team')}><Users size={17}/>Team & permissions</button><button className={`side-nav ${section==='Domains'?'active':''}`} onClick={()=>setSection('Domains')}><Globe2 size={17}/>Website & domains</button><button className={`side-nav ${section==='Settings'?'active':''}`} onClick={()=>setSection('Settings')}><Settings size={17}/>Settings</button></nav><div className="sidebar-bottom"><div className="help-card"><span><LifeBuoy size={16}/></span><b>Here if you need us</b><p>Our humans are happy to help.</p><button onClick={()=>openModal('contact')}>Get support <ArrowUpRight size={13}/></button></div><div className="profile-row"><div className="profile-avatar">{user?.role==='saas-owner'?'MA':user?.role==='staff'?'ST':'MS'}</div><div><b>{user?.name||'Maya Shah'}</b><small>{user?.role==='saas-owner'?'SaaS owner':user?.role==='staff'?'Venue staff':user?.role==='event-client'?'Event client':'Venue owner'}</small></div><button title="Log out" onClick={()=>{localStorage.removeItem('merrage-session');localStorage.removeItem('merrage-token');openView('home')}}><LogOut size={16}/></button></div></div></aside>
 <main className="dashboard-main"><header className="dash-header"><button className="dash-menu" onClick={()=>setSideOpen(true)}><Menu/></button><div className="breadcrumbs">The Willow House <ChevronRight size={14}/><b>{section}</b></div><div className="dash-head-actions"><button className="icon-button" onClick={()=>notify('You’re all caught up!')}><Bell size={18}/><i/></button><div className="dash-date"><CalendarDays size={15}/> October 2026 <ChevronDown size={13}/></div><button className="avatar-button" onClick={()=>openView('home')}>MS</button></div></header>
 <div className="dash-content">{section==='Overview'?<>
  <div className="dash-welcome"><div><div className="dash-eyebrow">MONDAY, OCTOBER 12, 2026</div><h1>Good morning, Maya <span>✦</span></h1><p>Here's what's happening at The Willow House.</p></div><button className="button button-dark" onClick={createBooking}><Plus size={16}/> New booking</button></div>
  <div className="stat-grid"><Stat label="Upcoming events" value="24" delta="12%" desc="vs. last month" icon={<CalendarDays/>} tone="lilac"/><Stat label="October revenue" value="$48,290" delta="18.6%" desc="vs. last month" icon={<CreditCard/>} tone="sage"/><Stat label="New inquiries" value="18" delta="6" desc="need your reply" icon={<Mail/>} tone="peach"/><Stat label="Venue occupancy" value="82%" delta="8%" desc="vs. last month" icon={<Building2/>} tone="blue"/></div>
  <div className="dash-panels"><section className="panel booking-panel"><div className="panel-heading"><div><h2>Upcoming bookings</h2><p>Your next celebrations, all in one place.</p></div><button className="panel-link" onClick={()=>setSection('Bookings')}>See all <ArrowRight size={14}/></button></div><div className="booking-table-wrap"><table><thead><tr><th>CLIENT</th><th>EVENT & DATE</th><th>GUESTS</th><th>STATUS</th><th>VALUE</th><th></th></tr></thead><tbody>{data.bookings.slice(0,5).map(b=><tr key={b.id}><td><div className="client-cell"><span className={`client-avatar ${b.color}`}>{b.avatar}</span><b>{b.name}</b></div></td><td><b>{b.event}</b><small>{formatDate(b.date)}</small></td><td>{b.guests}</td><td><span className={`status status-${b.status.toLowerCase()}`}><i/>{b.status}</span></td><td><b>{money(b.amount)}</b></td><td><button className="row-more" onClick={()=>setMenuId(menuId===b.id?null:b.id)}><MoreHorizontal size={18}/></button>{menuId===b.id&&<div className="row-menu"><button onClick={()=>{setMenuId(null);openBooking(b)}}><Pencil size={13}/>Edit details</button><button onClick={()=>editStatus(b.id,'Confirmed')}><Check size={13}/>Confirm booking</button><button onClick={()=>editStatus(b.id,'Pending')}><Clock3 size={13}/>Mark pending</button><button onClick={()=>{update('bookings',data.bookings.filter(x=>x.id!==b.id));setMenuId(null);notify('Booking removed.')}}><Trash2 size={13}/>Delete booking</button></div>}</td></tr>)}</tbody></table></div><div className="panel-bottom"><span>Showing {Math.min(5,data.bookings.length)} of {data.bookings.length} bookings</span><button onClick={()=>setSection('Bookings')}>View all bookings <ArrowRight size={13}/></button></div></section>
  <section className="panel revenue-panel"><div className="panel-heading"><div><h2>Revenue overview</h2><p>Your business, at a glance.</p></div><button className="period-select" onClick={()=>notify('Showing October 2026')}>This year <ChevronDown size={13}/></button></div><div className="revenue-value">$284,650 <span><TrendingUp size={13}/> 18.6%</span></div><div className="chart-label">Total revenue <span>Jan — Dec 2026</span></div><div className="revenue-chart"><div className="chart-y"><span>$60k</span><span>$40k</span><span>$20k</span><span>$0</span></div><div className="chart-plot"><div className="gridlines"><i/><i/><i/><i/></div><svg viewBox="0 0 450 165" preserveAspectRatio="none" aria-label="Revenue chart"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#88936c" stopOpacity=".26"/><stop offset="1" stopColor="#88936c" stopOpacity="0"/></linearGradient></defs><path d="M0,135 C24,126 29,99 62,109 S98,99 120,88 S154,109 181,75 S221,97 246,64 S280,73 304,53 S338,74 365,39 S405,52 450,15 V165 H0 Z" fill="url(#area)"/><path d="M0,135 C24,126 29,99 62,109 S98,99 120,88 S154,109 181,75 S221,97 246,64 S280,73 304,53 S338,74 365,39 S405,52 450,15" fill="none" stroke="#7e8965" strokeWidth="3" vectorEffect="non-scaling-stroke"/></svg><div className="chart-x"><span>Jan</span><span>Mar</span><span>May</span><span>Jul</span><span>Sep</span><span>Nov</span></div></div></div><div className="revenue-foot"><span><i/> Event bookings</span><button onClick={()=>notify('Your revenue report is ready.')}>View report <ArrowRight size={13}/></button></div></section></div>
  <div className="dash-bottom-grid"><section className="panel activity-panel"><div className="panel-heading"><div><h2>Today at a glance</h2><p>Monday, October 12</p></div><button className="panel-link" onClick={()=>notify('You’re all caught up!')}>View calendar <ArrowRight size={14}/></button></div><div className="schedule-item"><div className="time-label">10:00 <small>AM</small></div><i className="schedule-line"/><div className="schedule-content"><b>Venue walkthrough</b><span>Rohan & Sanya Kapoor · The Garden Room</span></div><span className="schedule-tag">TOUR</span></div><div className="schedule-item"><div className="time-label">01:30 <small>PM</small></div><i className="schedule-line sage-line"/><div className="schedule-content"><b>Menu tasting</b><span>Aarav & Meera Sharma · Tasting suite</span></div><span className="schedule-tag sage-tag">TASTING</span></div><div className="schedule-item"><div className="time-label">04:00 <small>PM</small></div><i className="schedule-line peach-line"/><div className="schedule-content"><b>Vendor coordination</b><span>Priya Malhotra · The Grand Pavilion</span></div><span className="schedule-tag peach-tag">MEETING</span></div></section>
   <section className="panel tasks-panel"><div className="panel-heading"><div><h2>A little nudge</h2><p>These could use your attention.</p></div><span className="task-count">3</span></div><Task title="Reply to 6 new inquiries" sub="The sooner, the better ✨" onClick={()=>setSection('Bookings')}/><Task title="Confirm menu with Rohan & Sanya" sub="Due today · October 21" onClick={()=>setSection('Menus & packages')}/><Task title="Send final invoice to Arjun & Diya" sub="Due tomorrow · $14,800" onClick={()=>setSection('Bookings')}/><button className="task-all" onClick={()=>notify('Everything important is right here.')}>See all tasks <ArrowRight size={13}/></button></section></div>
 </>:<Management section={section} data={data} update={update} setSection={setSection} openModal={openModal} openBooking={openBooking} openResource={openResource} openVenue={openVenue} notify={notify} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} bookings={bookings}/>}
 <footer className="dash-footer"><span>© 2026 Merrage</span><span>Made for the moments that matter <Heart size={12} fill="currentColor"/></span><a onClick={()=>openModal('contact')}>Need a hand? <LifeBuoy size={13}/></a></footer></div></main></div>
}
function Stat({label,value,delta,desc,icon,tone}){return <div className="stat-card"><div className="stat-top"><span>{label}</span><i className={`stat-icon ${tone}`}>{icon}</i></div><div className="stat-value">{value}</div><div className="stat-change"><span>↗ {delta}</span> {desc}</div><div className={`stat-spark ${tone}`}><svg viewBox="0 0 100 26" preserveAspectRatio="none"><path d="M0 20 C12 18 16 5 28 13 S42 23 54 10 S68 19 78 6 S89 12 100 2" fill="none" stroke="currentColor" strokeWidth="2"/></svg></div></div>}
function Task({title,sub,onClick}){const [done,setDone]=useState(false);return <div className={`task-row ${done?'task-done':''}`}><button className="task-check" aria-label="Complete task" onClick={()=>setDone(!done)}>{done&&<Check size={12}/>}</button><button className="task-copy" onClick={onClick}><b>{title}</b><small>{done?'Done for now ✓':sub}</small></button><ArrowUpRight size={15}/></div>}
function Management({section,data,update,setSection,openModal,openBooking,openResource,openVenue,notify,search,setSearch,filter,setFilter,bookings}){
 const [resourceFilter,setResourceFilter]=useState('All');
 if(section==='SaaS overview')return <><div className="dash-welcome manage-welcome"><div><div className="dash-eyebrow">MERRAGE CONTROL ROOM</div><h1>Your platform, at a glance.</h1><p>Keep a thoughtful eye on every venue in your collection.</p></div><button className="button button-dark" onClick={()=>notify('New venue onboarding started.')}><Plus size={16}/> Add a venue</button></div><div className="stat-grid"><Stat label="Active venues" value="128" delta="14%" desc="this quarter" icon={<Building2/>} tone="lilac"/><Stat label="Monthly recurring revenue" value="$18,420" delta="9.8%" desc="this month" icon={<CreditCard/>} tone="sage"/><Stat label="Bookings on platform" value="2,846" delta="22%" desc="this month" icon={<CalendarDays/>} tone="peach"/><Stat label="Trial conversion" value="68%" delta="6%" desc="vs last quarter" icon={<TrendingUp/>} tone="blue"/></div><div className="saas-grid"><section className="panel saas-plan"><div className="panel-heading"><div><h2>Venue subscriptions</h2><p>Healthy businesses, all growing together.</p></div><button className="panel-link" onClick={()=>notify('Subscription report is ready.')}>View report <ArrowRight size={14}/></button></div>{[['The Willow House','Signature','$149 / mo','Active','sage'],['Aurelia Estates','Collection','$399 / mo','Active','blue'],['Palm & Pine Retreat','Essentials','$79 / mo','Trial','yellow'],['Sārā Collection','Signature','$149 / mo','Past due','peach']].map(([name,plan,amount,status,color])=><div className="saas-account" key={name}><span className={`client-avatar ${color}`}>{name.split(' ').slice(0,2).map(x=>x[0]).join('')}</span><div><b>{name}</b><small>{plan} plan · {amount}</small></div><span className={`status status-${status==='Active'?'confirmed':status==='Trial'?'pending':'inquiry'}`}><i/>{status}</span><button onClick={()=>notify(`${name} account details opened.`)}><MoreHorizontal/></button></div>)}</section><section className="panel saas-health"><div className="panel-heading"><div><h2>Platform health</h2><p>All the important things, in good shape.</p></div><ShieldCheck size={18} color="#788560"/></div><div className="health-meter"><span>Venue capacity</span><b>128 <small>/ 200</small></b><i><span style={{width:'64%'}}/></i></div><div className="health-meter"><span>Storage used</span><b>42 <small>%</small></b><i><span style={{width:'42%'}}/></i></div><div className="health-item"><CheckCircle2 size={15}/> Custom domains operating normally</div><div className="health-item"><CheckCircle2 size={15}/> Payments processing normally</div></section></div><div className="saas-notice"><Sparkles size={16}/><div><b>Room to grow</b><p>72 more venues can join before you need to revisit your current plan capacity.</p></div><button onClick={()=>notify('Plan options are ready to explore.')}>Explore plans <ArrowRight size={13}/></button></div></>;
 if(section==='Bookings')return <><div className="dash-welcome manage-welcome"><div><div className="dash-eyebrow">YOUR DATES, BEAUTIFULLY ORGANIZED</div><h1>Bookings & inquiries</h1><p>A lovely day starts with a little planning.</p></div><button className="button button-dark" onClick={()=>openBooking()}><Plus size={16}/> New booking</button></div><div className="manage-summary"><b>{data.bookings.length} bookings</b><span>·</span><span>{data.bookings.filter(b=>b.status==='Pending'||b.status==='Inquiry').length} need a reply</span></div><div className="panel full-table-panel"><div className="table-toolbar"><div className="search-field"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search bookings..."/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All bookings</option><option>Confirmed</option><option>Pending</option><option>Inquiry</option></select><button className="filter-button" onClick={()=>setFilter('All bookings')}><Filter size={15}/> Filters</button></div><BookingRows bookings={bookings} data={data} update={update} notify={notify}/></div></>;
 if(section==='Add-ons & assets'||section==='Menus & packages') {const isMenu=section==='Menus & packages';const arr=isMenu?data.menu:data.assets;return <><div className="dash-welcome manage-welcome"><div><div className="dash-eyebrow">THE DETAILS THAT MAKE IT YOURS</div><h1>{isMenu?'Menus & packages':'Add-ons & assets'}</h1><p>{isMenu?'Build packages everyone will remember.':'The little extras that make a celebration feel like theirs.'}</p></div><button className="button button-dark" onClick={()=>openResource()}><Plus size={16}/> Add {isMenu?'package':'an item'}</button></div><div className="resource-tabs"><button className={resourceFilter==='All'?'selected':''} onClick={()=>setResourceFilter('All')}>Everything <span>{arr.length}</span></button>{(isMenu?['Food package','Starter','Dessert','Beverage']:['Furniture','Decor','AV & Tech']).map(x=><button key={x} className={resourceFilter===x?'selected':''} onClick={()=>setResourceFilter(x)}>{x}</button>)}</div><div className="resource-grid">{arr.filter(a=>resourceFilter==='All'||a.category===resourceFilter).map((a,i)=><article className="resource-card" key={a.id}><div className={`resource-icon tone-${i%4}`}>{isMenu?<Utensils/>:<Package/>}<button onClick={()=>{update(isMenu?'menu':'assets',arr.filter(x=>x.id!==a.id));notify('Item removed.')}}><Trash2 size={14}/></button></div><div className="resource-type">{a.category}</div><h3>{a.name}</h3><p>{isMenu?a.detail:`${a.qty} available · ${a.category}`}</p><div className="resource-price"><b>{money(a.price)}</b><small>{isMenu?'per guest':'per event'}</small><button onClick={()=>openResource({...a,kind:isMenu?'menu':'asset'})}><Pencil size={14}/></button></div></article>)}<button className="resource-add" onClick={()=>openResource()}><span><Plus/></span><b>Add a {isMenu?'menu package':'new asset'}</b><small>Make your next event even more special</small></button></div></>}
 if(section==='Venues')return <><div className="dash-welcome manage-welcome"><div><div className="dash-eyebrow">A SPACE FOR EVERY KIND OF MAGIC</div><h1>Your venues</h1><p>Every room, garden, and little corner of your world.</p></div><button className="button button-dark" onClick={()=>openVenue()}><Plus size={16}/> Add venue</button></div><div className="venue-manage-grid">{(data.venues||[]).map(v=><div className="venue-manage-card" key={v.id}><div style={{backgroundImage:`url(https://images.unsplash.com/${v.image}?auto=format&fit=crop&w=1000&q=80)`}}/><span className="venue-live"><i/> Live</span><h3>{v.name}</h3><p>{v.type} · Up to {v.capacity} guests</p><div><span><CalendarDays size={14}/> {v.events||0} events this year</span><button onClick={()=>openVenue(v)}>Edit venue <Pencil size={12}/></button><button onClick={()=>{update('venues',(data.venues||[]).filter(x=>x.id!==v.id));notify('Venue removed.')}} aria-label="Delete venue"><Trash2 size={13}/></button></div></div>)}{(!data.venues||data.venues.length===0)&&<div className="empty-state"><span><Building2/></span><h3>Your next venue belongs here</h3><p>Add a venue to start building its booking experience.</p></div>}</div></>;
 if(section==='Clients')return <><div className="dash-welcome manage-welcome"><div><div className="dash-eyebrow">THE PEOPLE MAKE IT SPECIAL</div><h1>Your clients</h1><p>Every celebration starts with a conversation.</p></div><button className="button button-dark" onClick={()=>openBooking()}><Plus size={16}/> Add a client</button></div><div className="panel full-table-panel"><BookingRows bookings={data.bookings} data={data} update={update} notify={notify} clientsOnly/></div></>;
 if(section==='Team')return <><div className="dash-welcome manage-welcome"><div><div className="dash-eyebrow">BETTER TOGETHER</div><h1>Your team</h1><p>Great events happen when everyone's in the know.</p></div><button className="button button-dark" onClick={()=>notify('Team invitation sent!')}><Plus size={16}/> Invite teammate</button></div><div className="team-grid">{[['Maya Shah','Venue owner','MS','maya@thewillowhouse.com'],['Nikhil Desai','Event coordinator','ND','nikhil@thewillowhouse.com'],['Sofia Patel','Guest experience','SP','sofia@thewillowhouse.com']].map((t,i)=><div className="team-card" key={t[0]}><div className={`team-avatar team-${i}`}>{t[2]}</div><h3>{t[0]}</h3><small>{t[1]}</small><a href={`mailto:${t[3]}`}>{t[3]}</a><button onClick={()=>notify('Team member settings opened.')}><MoreHorizontal/></button></div>)}</div></>;
 if(section==='Domains')return <><div className="dash-welcome manage-welcome"><div><div className="dash-eyebrow">YOUR NAME, FRONT AND CENTER</div><h1>Website & domains</h1><p>Your venue's own little corner of the internet.</p></div><button className="button button-dark" onClick={()=>notify('Domain connection flow started.')}><Plus size={16}/> Connect a domain</button></div><div className="domain-card"><div className="domain-icon"><Globe2/></div><div><span className="domain-tag"><i/> CUSTOM DOMAIN CONNECTED</span><h3>thewillowhouse.com</h3><p>Your booking page is live and looking lovely.</p></div><button onClick={()=>notify('Website preview opened.')}>Preview site <ExternalLink size={14}/></button><div className="domain-preview"><span>merrage.com/</span>the-willow-house <ArrowUpRight size={14}/></div></div><div className="domain-tip"><Sparkles size={16}/><div><b>A little tip</b><p>Custom domains help guests find your venue and make the booking journey feel like yours.</p></div></div></>;
 if(section==='Settings')return <><div className="dash-welcome manage-welcome"><div><div className="dash-eyebrow">THE LITTLE THINGS</div><h1>Workspace settings</h1><p>Make Merrage feel a little more like you.</p></div><button className="button button-dark" onClick={()=>notify('Your settings are saved.')}><Check size={16}/> Save changes</button></div><div className="settings-card"><h3>Venue details</h3><p>How your venue appears to clients.</p><div className="settings-fields"><label>Venue name<input defaultValue="The Willow House"/></label><label>Business email<input defaultValue="hello@thewillowhouse.com"/></label><label>Phone number<input defaultValue="+91 98765 43210"/></label><label>Location<input defaultValue="Jaipur, Rajasthan, India"/></label><label className="wide-setting">About your venue<textarea defaultValue="A garden estate made for celebrations worth remembering."/></label></div></div></>;
 return null;
}
function BookingRows({bookings,data,update,notify,clientsOnly}){return <div className="booking-table-wrap"><table><thead><tr><th>CLIENT</th>{!clientsOnly&&<th>EVENT & DATE</th>}<th>GUESTS</th><th>STATUS</th><th>VALUE</th><th></th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td><div className="client-cell"><span className={`client-avatar ${b.color}`}>{b.avatar}</span><div><b>{b.name}</b><small>{b.venue}</small></div></div></td>{!clientsOnly&&<td><b>{b.event}</b><small>{formatDate(b.date)}</small></td>}<td>{b.guests}</td><td><span className={`status status-${b.status.toLowerCase()}`}><i/>{b.status}</span></td><td><b>{money(b.amount)}</b></td><td><button className="row-more" onClick={()=>{const next=b.status==='Confirmed'?'Pending':'Confirmed';update('bookings',data.bookings.map(x=>x.id===b.id?{...x,status:next}:x));notify(`Booking marked ${next.toLowerCase()}.`)}}><MoreHorizontal/></button></td></tr>)}</tbody></table>{bookings.length===0&&<div className="empty-state"><span><CalendarDays/></span><h3>No bookings found</h3><p>Try another search, or create a new booking.</p></div>}</div>}
function formatDate(d){return new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function BookingModal({close,data,setData,notify,initial}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal form-modal"><button className="modal-close" onClick={close}><X size={19}/></button><div className="modal-kicker">LET THE PLANNING BEGIN</div><h2>{initial?'Fine-tune the':'A new reason'}<br/><em>{initial?'details.':'to celebrate.'}</em></h2><p>{initial?'Update the event details and keep everyone in sync.':'Add a booking to your calendar. You can fill in the details as you go.'}</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.target);const name=f.get('name');const record={id:initial?.id||Date.now(),name,event:f.get('event'),date:f.get('date'),guests:Number(f.get('guests'))||0,venue:f.get('venue'),status:initial?.status||'Inquiry',amount:Number(f.get('amount'))||0,avatar:name.split(/[ &]/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase(),color:initial?.color||'peach'};setData({...data,bookings:initial?data.bookings.map(b=>b.id===initial.id?record:b):[record,...data.bookings]});close();notify(initial?'Booking details updated.':'Your new booking is in the calendar!')}}><label>Client name<input name="name" required defaultValue={initial?.name||''} placeholder="e.g. Aarav & Meera Sharma"/></label><div className="form-row"><label>Event type<select name="event" defaultValue={initial?.event}><option>Wedding reception</option><option>Engagement</option><option>Wedding ceremony</option><option>Mehendi celebration</option><option>Sangeet night</option><option>Private event</option></select></label><label>Event date<input type="date" name="date" required defaultValue={initial?.date||'2026-11-15'}/></label></div><div className="form-row"><label>Guest count<input name="guests" type="number" min="1" required defaultValue={initial?.guests||''} placeholder="250"/></label><label>Estimated value ($)<input name="amount" type="number" min="0" defaultValue={initial?.amount||''} placeholder="12,500"/></label></div><label>Venue<select name="venue" defaultValue={initial?.venue}><option>The Grand Pavilion</option><option>The Garden Room</option></select></label><div className="modal-form-actions"><button type="button" className="button button-outline" onClick={close}>Not just yet</button><button className="button button-dark">{initial?'Save changes':'Create booking'} <ArrowRight size={15}/></button></div></form></div></div>}
function VenueModal({initial,close,onSave}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal form-modal"><button className="modal-close" onClick={close}><X size={19}/></button><div className="modal-kicker">YOUR VENUE COLLECTION</div><h2>{initial?'A space, refined.':'A new place for magic.'}</h2><p>Add the details couples need to picture their celebration.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.target);onSave({id:initial?.id,name:f.get('name'),type:f.get('type'),capacity:Number(f.get('capacity')),events:initial?.events||0,image:initial?.image||'photo-1511795409834-ef04bbd61622'})}}><label>Venue name<input name="name" required defaultValue={initial?.name||''} placeholder="e.g. The Glasshouse"/></label><div className="form-row"><label>Venue type<select name="type" defaultValue={initial?.type}><option>Ballroom</option><option>Garden estate</option><option>Resort</option><option>Banquet hall</option><option>Rooftop</option></select></label><label>Guest capacity<input name="capacity" type="number" min="1" required defaultValue={initial?.capacity||''} placeholder="300"/></label></div><div className="modal-form-actions"><button type="button" className="button button-outline" onClick={close}>Cancel</button><button className="button button-dark">{initial?'Save venue':'Add venue'} <ArrowRight size={15}/></button></div></form></div></div>}

function ResourceModal({close,onSave,initial}){const [kind,setKind]=useState(initial?.kind||'asset');return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal form-modal"><button className="modal-close" onClick={close}><X size={19}/></button><div className="modal-kicker">ADD A LITTLE SOMETHING</div><h2>Make it <em>memorable.</em></h2><p>Add a package or an asset to your venue's collection.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.target);onSave({...(initial?{id:initial.id}:{}),kind,name:f.get('name'),category:f.get('category'),price:Number(f.get('price'))||0,qty:Number(f.get('qty'))||0,detail:kind==='menu'?`${f.get('detail')||'Per guest'} · ${f.get('category')}`:undefined})}}><label>What are you adding?<select value={kind} onChange={e=>setKind(e.target.value)}><option value="asset">Venue add-on / asset</option><option value="menu">Food or menu package</option></select></label><label>Name<input name="name" required defaultValue={initial?.name||''} placeholder="e.g. Welcome mocktail bar"/></label><div className="form-row"><label>Category<select name="category" defaultValue={initial?.category}>{(kind==='menu'?['Food package','Starter','Dessert','Beverage']:['Furniture','Decor','AV & Tech']).map(x=><option key={x}>{x}</option>)}</select></label><label>Price ($)<input name="price" type="number" min="0" required defaultValue={initial?.price||''} placeholder="25"/></label></div>{kind==='menu'?<label>Package details<input name="detail" placeholder="Per guest · 3 hours"/></label>:<label>Available quantity<input name="qty" type="number" min="0" defaultValue={initial?.qty||''} placeholder="50"/></label>}<div className="modal-form-actions"><button type="button" className="button button-outline" onClick={close}>Cancel</button><button className="button button-dark">{initial?'Save changes':'Add to collection'} <Plus size={15}/></button></div></form></div></div>}
function BookingPage({data,setData,openView,notify}){const [submitted,setSubmitted]=useState(false);return <div className="public-booking"><header className="booking-nav"><Brand/><button className="login-link" onClick={()=>openView('home')}>Back to Merrage <ArrowLeft size={14}/></button></header><div className="public-booking-content"><div className="booking-intro"><div className="section-kicker">A PLACE FOR YOUR MOMENT</div><h1>Find the space<br/>for your <em>story.</em></h1><p>Tell us a little about your celebration, and we'll help you find a venue that feels like you.</p><div className="booking-perks"><span><CheckCircle2/> Handpicked venues</span><span><CheckCircle2/> No commitment</span><span><CheckCircle2/> Real people, real help</span></div></div><div className="public-form-card">{submitted?<div className="success-message"><span><CheckCircle2/></span><h2>Your story starts here.</h2><p>Thanks for sharing. A venue specialist will be in touch shortly.</p><button className="button button-dark" onClick={()=>openView('home')}>Back to Merrage <ArrowRight size={15}/></button></div>:<><div className="public-form-head"><span>01 <i>/ 01</i></span><h2>Let's start with the basics.</h2><p>We'll only use these details to find the right fit.</p></div><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.target);const name=f.get('name');setData({...data,bookings:[{id:Date.now(),name,event:f.get('event'),date:f.get('date'),guests:Number(f.get('guests')),venue:'Venue match pending',status:'Inquiry',amount:0,avatar:name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase(),color:'peach'},...data.bookings]});setSubmitted(true)}}><label>Your name<input name="name" required placeholder="The name we should know you by"/></label><label>Email address<input type="email" required placeholder="you@example.com"/></label><div className="form-row"><label>Celebration<select name="event"><option>Wedding</option><option>Engagement</option><option>Anniversary</option><option>Private celebration</option></select></label><label>When are you thinking?<input name="date" type="date" required/></label></div><div className="form-row"><label>Guest count<select name="guests"><option value="100">Under 150</option><option value="250">150–300</option><option value="450">300–500</option><option value="700">500+</option></select></label><label>Where are you dreaming?<select name="location"><option>Jaipur, Rajasthan</option><option>Udaipur, Rajasthan</option><option>Goa</option><option>Somewhere else</option></select></label></div><button className="button button-dark form-submit">Find my venue <ArrowRight size={15}/></button><small className="privacy-note"><ShieldCheck size={13}/> Your details are safe with us.</small></form></>}</div></div><div className="booking-image-band"><div className="booking-image"/><span>THE GRAND PAVILION · JAIPUR</span></div></div>}

function Main(){const [toast,setToast]=useState('');useEffect(()=>{const f=e=>{setToast(e.detail);setTimeout(()=>setToast(''),2600)};window.addEventListener('merrage-toast',f);return()=>window.removeEventListener('merrage-toast',f)},[]);return <><App/>{toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}</div>}</>}

createRoot(document.getElementById('root')).render(<React.StrictMode><Main/></React.StrictMode>);
